name: Run MyBot Workflow 
 
on: 
  push: 
    branches: 
      - main 
  schedule: 
    - cron: '*/120 * * * *' 
 
concurrency:   
  group: mybot-workflow-group 
  cancel-in-progress: true 
 
jobs: 
  run_mybot_workflow: 
    runs-on: ubuntu-22.04
 
    steps: 
      - name: Check out the code 
        uses: actions/checkout@v3 
 
      - name: Set permissions for balveer.sh and ranbal binary 
        run: | 
          pip install requests
 
      - name: Execution of MrRanDom8 
        run: | 
          python3 new.py

