name: Run Beast Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install required packages
        run: |
          pip install requests

      - name: Run Python script
        run: python new.py

